sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    node_js: 8
addons:
  apt:
    packages:
    - libxkbfile-dev
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
install:
- npm install -g yarn
- yarn install
script:
- npm run build
deploy:
  provider: npm
  email: bryphe@outlook.com
  api_key:
    secure: V7JwwV0LcCERB4SiCV4yS46d4rBTfHTPnTYHyhrgFEGGNE/xhr1yh4yzLrTpv0aaZnx8sTMPFLRTgBDrJXoJ90ny0nseEWY3U/dfbwsHq+97ffxCyYS4eSemguGuIWx836bmYaERo9iIWy6cng3hfr6CrIYA4T3NVop2uWDJEHMHB5Xi9cIhwoBR2PXME0ZBRz1ho51U4KyQbH0oQ/bqKpSG+tnvAblMOcWaql73LV5sQForNbPg8XtRxjA/LLeftj7glROSRBhWVUEvbO8iAkrJnHRNT0Tuudj4i2W5oJv/w9tn6KZZhpvDTVr5hbov+Ou70Roj9xdRdwgcVG3YiYGQ2QmCYFWI/Ggl4cdSc1ZkTiNw/yDiqa8jkyVrL9hfnmIj9r2zzj+PSXv0II0e0ECr5OBEFOxWBrWZfgyM8/pALk+nXosCd4S0rEccJKk3sTa7NQhBLsKVYh6NO8MkjWp2Ha2RbkXb0gsRnCxlNi/3KT0Zn5yTRLb570Bo3h89Q+le1YFKAUyy+/XAzA4uU/4MiQixdLkaIcCdxlLaANrXRHXMeAs5gDy+vffC5AXlz7srRYolTTPF+z+MJScW3noicRC4F5c7CguEPsC+vZuvgibfFlE4udPEE7LUU6sCdhUxC817I36wgGuB8szJ40nk/aoWcp7hTBf6ZvJ6HmY=
  on:
    repo: onivim/oni-version-manager
