sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    node_js: 8
addons:
  apt:
    packages:
    - libxkbfile-dev
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
install:
- npm install -g yarn
- yarn install
script:
- npm run build
